In [56]:
# TODO based on https://www.tensorflow.org/text/tutorials/text_generation

import tensorflow as tf

import numpy as np
import os
import time

print(tf.__version__)

2.5.0


In [57]:
full_text = open('words_alpha.txt', 'rb').read().decode(encoding='utf-8')
text = ''
seq_length = 30
for word in full_text.split():
    if len(word) < 4:
        continue
    else:
        word = '_' + word
        for i in range(0, seq_length-len(word)):
            word = word + '*'
    text = text + word

print(f'Length of text: {len(text)} characters')
print(text[:300])

Length of text: 11025662 characters
_aahed************************_aahing***********************_aahs*************************_aalii************************_aaliis***********************_aals*************************_aani*************************_aardvark*********************_aardvarks********************_aardwolf*********************


In [58]:
vocab = sorted(set(text))
print(f'{len(vocab)} unique characters')
print(vocab)

28 unique characters
['*', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


In [59]:
ids_from_chars = tf.keras.layers.experimental.preprocessing.StringLookup(
    vocabulary=list(vocab), mask_token=None)

chars_from_ids = tf.keras.layers.experimental.preprocessing.StringLookup(
    vocabulary=ids_from_chars.get_vocabulary(), invert=True, mask_token=None)

def text_from_ids(ids):
  return tf.strings.reduce_join(chars_from_ids(ids), axis=-1)

In [64]:
all_ids = ids_from_chars(tf.strings.unicode_split(text, 'UTF-8'))
ids_dataset = tf.data.Dataset.from_tensor_slices(all_ids)

for element in ids_dataset.take(seq_length):
    print(element, chars_from_ids(element).numpy().decode('utf-8'))

tf.Tensor(2, shape=(), dtype=int64) _
tf.Tensor(3, shape=(), dtype=int64) a
tf.Tensor(3, shape=(), dtype=int64) a
tf.Tensor(10, shape=(), dtype=int64) h
tf.Tensor(7, shape=(), dtype=int64) e
tf.Tensor(6, shape=(), dtype=int64) d
tf.Tensor(1, shape=(), dtype=int64) *
tf.Tensor(1, shape=(), dtype=int64) *
tf.Tensor(1, shape=(), dtype=int64) *
tf.Tensor(1, shape=(), dtype=int64) *
tf.Tensor(1, shape=(), dtype=int64) *
tf.Tensor(1, shape=(), dtype=int64) *
tf.Tensor(1, shape=(), dtype=int64) *
tf.Tensor(1, shape=(), dtype=int64) *
tf.Tensor(1, shape=(), dtype=int64) *
tf.Tensor(1, shape=(), dtype=int64) *
tf.Tensor(1, shape=(), dtype=int64) *
tf.Tensor(1, shape=(), dtype=int64) *
tf.Tensor(1, shape=(), dtype=int64) *
tf.Tensor(1, shape=(), dtype=int64) *
tf.Tensor(1, shape=(), dtype=int64) *
tf.Tensor(1, shape=(), dtype=int64) *
tf.Tensor(1, shape=(), dtype=int64) *
tf.Tensor(1, shape=(), dtype=int64) *
tf.Tensor(1, shape=(), dtype=int64) *
tf.Tensor(1, shape=(), dtype=int64) *
tf.Tensor(1

In [65]:
# TODO read karpathi to see how he chooses sequence length and if it's important
# maybe longer is better? but we don't want to keep context between words

# try truncating and padding after the stop token
# sequence length = shortest word length, change the start character into _

sequences = ids_dataset.batch(seq_length, drop_remainder=True)

for seq in sequences.take(5):
  print(seq, text_from_ids(seq))

tf.Tensor(
[ 2  3  3 10  7  6  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1], shape=(30,), dtype=int64) tf.Tensor(b'_aahed************************', shape=(), dtype=string)
tf.Tensor(
[ 2  3  3 10 11 16  9  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1], shape=(30,), dtype=int64) tf.Tensor(b'_aahing***********************', shape=(), dtype=string)
tf.Tensor(
[ 2  3  3 10 21  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1], shape=(30,), dtype=int64) tf.Tensor(b'_aahs*************************', shape=(), dtype=string)
tf.Tensor(
[ 2  3  3 14 11 11  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1], shape=(30,), dtype=int64) tf.Tensor(b'_aalii************************', shape=(), dtype=string)
tf.Tensor(
[ 2  3  3 14 11 11 21  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1], shape=(30,), dtype=int64) tf.Tensor(b'_aaliis***********************', shape=(), dtype=string)


In [66]:
def split_input_target(sequence):
    print(sequence)
    input_text = sequence
    target_text = tf.concat([sequence[1:], [1]], 0) # pad with extra *
    return input_text, target_text
dataset = sequences.map(split_input_target)
for input_example, target_example in dataset.take(1):
    print("Input :", text_from_ids(input_example).numpy())
    print("Target:", text_from_ids(target_example).numpy())

Tensor("args_0:0", shape=(30,), dtype=int64)
Input : b'_aahed************************'
Target: b'aahed*************************'


In [67]:
BATCH_SIZE = 64
BUFFER_SIZE = 10000

dataset = (
    dataset
    .shuffle(BUFFER_SIZE)
    .batch(BATCH_SIZE, drop_remainder=True)
    .prefetch(tf.data.experimental.AUTOTUNE))

### Define the model
We use an RNN with GRUs defined in rnn_gru_model.py

In [68]:
from rnn_gru_model import RnnGRUModel
model = RnnGRUModel()

### Try the untrained model on the first sequence

In [69]:
for input_example_batch, target_example_batch in dataset.take(1):
    example_batch_predictions = model(input_example_batch)
    print(example_batch_predictions.shape, "# (batch_size, sequence_length, vocab_size)")
    
# vocab size is 29 because of [UNK]
# TODO we don't actually need [UNK] since input involves all possible characters already
model.summary()

(64, 30, 29) # (batch_size, sequence_length, vocab_size)
Model: "rnn_gru_model_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      multiple                  7424      
_________________________________________________________________
gru_4 (GRU)                  multiple                  3938304   
_________________________________________________________________
dense_8 (Dense)              multiple                  29725     
_________________________________________________________________
dense_9 (Dense)              multiple                  870       
Total params: 3,976,323
Trainable params: 3,976,323
Non-trainable params: 0
_________________________________________________________________


In [70]:
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)
sampled_indices = tf.squeeze(sampled_indices, axis=-1).numpy()
sampled_indices

array([21, 13,  0, 26,  4,  5, 17, 21, 24,  1, 17, 27,  1, 25,  8,  8, 28,
       11, 17,  8,  1,  0,  3,  2, 14, 13, 15,  7,  3,  0])

In [71]:
print("Input:\n", text_from_ids(input_example_batch[0]).numpy().decode('utf-8'))
print("Next Char Predictions:\n", text_from_ids(sampled_indices).numpy().decode('utf-8'))

Input:
 _aguroth**********************
Next Char Predictions:
 sk[UNK]xbcosv*oy*wffziof*[UNK]a_lkmea[UNK]


In [73]:
loss = tf.losses.SparseCategoricalCrossentropy(from_logits=True)
example_batch_loss = loss(target_example_batch, example_batch_predictions)
mean_loss = example_batch_loss.numpy().mean()
print("Prediction shape: ", example_batch_predictions.shape, " # (batch_size, sequence_length, vocab_size)")
print("Mean loss:        ", mean_loss)

Prediction shape:  (64, 30, 29)  # (batch_size, sequence_length, vocab_size)
Mean loss:         3.3644955


In [74]:
# A newly initialized model shouldn't be too sure of itself, the output logits should
# all have similar magnitudes. To confirm this you can check that the exponential of the mean
# loss is approximately equal to the vocabulary size. A much higher loss means the model is
# sure of its wrong answers, and is badly initialized:

tf.exp(mean_loss).numpy()

28.918903

### Train the model

In [75]:
model.compile(optimizer='adam', loss=loss)

In [76]:
# Directory where the checkpoints will be saved
checkpoint_dir = 'training_checkpoints'
# Name of the checkpoint files
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt_{epoch}")

checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_prefix,
    save_weights_only=True)

In [80]:
EPOCHS = 5

In [81]:
history = model.fit(dataset, epochs=EPOCHS, callbacks=[checkpoint_callback])

Epoch 1/5
5742/5742 [==============================] - 805s 140ms/step - loss: 0.5863
Epoch 2/5
5742/5742 [==============================] - 817s 142ms/step - loss: 0.5671
Epoch 3/5
5742/5742 [==============================] - 860s 150ms/step - loss: 0.5701
Epoch 4/5
5742/5742 [==============================] - 876s 153ms/step - loss: 0.5759
Epoch 5/5
5742/5742 [==============================] - 858s 149ms/step - loss: 0.5801


### Create wrapper which generates and evaluates word plausiblity

In [100]:
from rnn_plausiblewords import RnnWordPlausibilityEvaluator
import logging
model_wrapper = RnnWordPlausibilityEvaluator(logging,
                                             model=model,
                                             ids_from_chars=ids_from_chars,
                                             chars_from_ids=chars_from_ids,
                                             temperature=0.8)

In [103]:
# TODO generate some words using Spolling Bree letters and see how the models agree or disagree
def create_words(given_model, num_words):
    for m in range(num_words):
      states = None
      next_char = tf.constant(['_'])
      result = [next_char]

      for n in range(100):
        next_char, states = given_model.generate_one_step(next_char, states=states)
        result.append(next_char)
        if next_char == '*':
          break

      result = tf.strings.join(result)
      end = time.time()
      print(result[0].numpy().decode('utf-8'))

create_words(model_wrapper, 10)

_udex*
_coller*
_elvies*
_agmanies*
_commonied*
_compic*
_cands*
_candological*
_dgorm*
_oxyphyl*


In [105]:
print(model_wrapper.evaluate_word('test'))
print(model_wrapper.evaluate_word('testestest'))

4.7846328020095825
24.958137571811676


### Save and load the model

In [92]:
## Save the model weights only
model.save_weights("base_model_saved_weights")

In [93]:
## Save the layers needed to regenerate ModelWrapper
tf.saved_model.save(chars_from_ids, 'chars_from_ids')
tf.saved_model.save(ids_from_chars, 'ids_from_chars')


FOR DEVS: If you are overwriting _tracking_metadata in your class, this property has been used to save metadata in the SavedModel. The metadta field will be deprecated soon, so please move the metadata to a different file.
INFO:tensorflow:Assets written to: chars_from_ids/assets

FOR DEVS: If you are overwriting _tracking_metadata in your class, this property has been used to save metadata in the SavedModel. The metadta field will be deprecated soon, so please move the metadata to a different file.
INFO:tensorflow:Assets written to: ids_from_chars/assets


2022-01-18 14:41:24.907000: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.


In [ ]:
# loaded_model.load_weights("base_model_saved_weights")